### ISSUE TITLE
[ Facebook ] - verify token use

### ISSUE THREAD

**Issue by lisataylor5472** [lisataylor5472/lisataylor5472#51]
- [x] Does the token that we get from new auth flow work with our collection? (eg can we pull reports?)
- API returns `data: []` --- no permissions error 
- [x] Does the token that we get from the new auth flow work with postbacks? (can we send CAPI events?)
- API returns `data: []` --- no permissions error 
- [ ] Does our old auth for the “gamesight-console-admin” system user look the same on API calls as the new tokens? 
- [ ] If so, can we migrate all existing integrations to GDI’s with our system token as a migration path? 
- [ ] If not, we can just put a little magic string in the GDI that says “I am old style”
